-- table created at 2016-02-14 
 CREATE TABLE IF NOT EXISTS `mariana`.`comments` ( 
`id` INTEGER PRIMARY KEY ,
`date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
`last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  )
 ENGINE = InnoDB